import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Miro from '../components/miro'
import { Flex } from "@chakra-ui/react"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* className={styles.title} */}
        <h1 id="main-title" className="main-title-class">
          miro embed
        </h1>
        
        <div className="miro_main">
          <div className="bar_top" />
          <Flex color="white">
            <div className="bar_left" />
            <div className="miro">
              <Miro />
            </div>
            <div className="bar_right" />
          </Flex>
          <div className="bar_bottom" />
        </div>

{/* 
        <div className={styles.embed}>
          <iframe className="css-5bxaph" width="768" height="432" src="https://miro.com/app/live-embed/o9J_l0yiJfI=/?moveToViewport=-3906,-3996,8198,8677&embedAutoplay=true#toolbar=0" frameBorder="0" scrolling="no" allowFullScreen></iframe>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
